#ifndef SPLINE_DEFINITIONS_H
#define SPLINE_DEFINITIONS_H

enum SplineBoundaryCondition {
    NATURAL_SPLINE,
    CLAMPED,
    SECOND_DERIVATIVE_FIXED,
    NOT_A_KNOT_CONDITION,
    PERIODIC_CONDITION
};

#endif // SPLINE_DEFINITIONS_H
